### ISSUE TITLE
Microsoft word not rendering at all

### ISSUE THREAD

**Issue by ecstrema** [MarcSabatella/Campania#8]
Apparently Microsoft Word does not render the campania font at all, is this something related to the font itself, or is it microsoft's fault.

**Comment by MarcSabatella** [comment]
I'm not a Word expert by any means, but from what I've read, some programs require you to explicitly enable OpenType features.  So you might have to pore through the Word documentation to see how.

From what I have been able to piece together, it has to do with disagreement between vendors over which features should be enabled by default, but there doesn't seem to be a way for a font to force vendors to enable the features it needs.  If you learn otherwise, I'm happy to do whatever I would need to do to get that to work.

**Comment by ecstrema** [comment]
You are right: in Words, OpenType features [need to be explicitely enabled](https://medialoot.com/blog/how-to-enable-opentype-features-in-word-photoshop-and-illustrator/).
